Release dlocate 1.0

diff --git a/dlocate b/dlocate
--- a/dlocate
+++ b/dlocate
@@ -13,59 +13,61 @@
 # hacked by cas to support multiple string/package arguments
 # hacked by cas to add simplistic emulation of 'dpkg -l'
 
-DLOCATEDB=/var/lib/dlocate/dlocatedb
+DLOCATEDB=/var/lib/dlocate/dlocatedb.txt
 DPKGLIST=/var/lib/dlocate/dpkg-list
 DPKG_INFO=/var/lib/dpkg/info
 
-if [ -x /usr/bin/locate.findutils ] ; then
-    # locate package is installed
-    LOCATE='/usr/bin/locate.findutils'
-else
-    # slocate diverts locate
-    LOCATE=$(/usr/sbin/dpkg-divert --truename /usr/bin/locate)
-fi
-
 function dlocate_help {
   cat <<__EOF__
-Usage: dlocate [option] [string...]
+Usage: dlocate [option...] [command] [PATTERN...]
 
-Options:
-  (no option) string  list all records that match
-  -S          string      list records where files match
-  -L          package     list all files in package
-  -l          package     almost-emulation of 'dpkg -l'
-  -s          package     print package's status
-  -ls         package     'ls -ldF' of all files in package
-  -du         package     'du -sck' of all files in package
-  -conf       package     list conffiles in package
-  -lsconf     package     'ls -ldF' of conffiles in package
-  -md5sum     package     list package's md5sums (if any)
-  -md5check   package     check package's md5sums (if any)
-  -man        package     list package's man pages (if any)
-  -lsman      package     list full path/filenames of man pages
-  -lsbin      package     list full path/filenames of executable files
+Commands:
+  DEFAULT/none PATTERN   list records that match either package or files names
+  -S           PATTERN   list records that match filenames
 
-  --                      stop processing options.  remainder of
-                          command-line is filename(s)
+  -L           package   list all files in package
+  -l           package   almost-emulation of 'dpkg -l'
+  -s           package   print package's status
+  -ls          package   'ls -ldF' of all files in package
+  -du          package   'du -sck' of all files in package
+  -conf        package   list conffiles in package
+  -lsconf      package   'ls -ldF' of conffiles in package
+  -md5sum      package   list package's md5sums (if any)
+  -md5check    package   check package's md5sums (if any)
+  -man         package   list package's man pages (if any)
+  -lsman       package   list full path/filenames of man pages
+  -lsbin       package   list full path/filenames of executable files
 
-  --ignore-case, -i       ignore case when search for filenames or
-                          package names.
+  --                    stop processing commands and options.  remainder of
+                        command-line is filename(s)
 
-  -h                      display this help message and exit.
-  -V                      display dlocate's version number and exit.
+The -l, and -S commands are approximately the same as the equivalent dpkg
+options except that the search is performed using regular expressions
+rather than fixed strings.
 
-  The -L, -s, and -S commands are roughly analagous to the
-  equivalent dpkg commands.
+Regular Expression Options (see grep(1) for details):
+
+  -E, --extended-regexp
+  -F, --fixed-strings
+  -G, --basic-regexp
+  -P, --perl-regexp
+
+  -w, --word-regexp     restrict matches to whole words
+  -i, --ignore-case     case-insensitive match
+
+Miscellaneous Options:
+
+  -h, -H, --help          display this help message and exit.
+  -V, --version           display dlocate's version number and exit.
+  -v, --verbose, --debug  verbose/debug output
 __EOF__
   exit 1
 }
 
 function dlocate_version {
-  #VERSION_BANNER=$(grep-dctrl -X -P dlocate -n -s Version -d \
-  #  /var/lib/dpkg/status | sed -e '2s/.*/(&)/')
-  VERSION_BANNER="0.96.1"
-  echo "dlocate version "$VERSION_BANNER
-  exit
+  VERSION_BANNER="1.0"
+  echo "dlocate version $VERSION_BANNER"
+  exit 0
 }
 
 function dlocate_option_error () {
@@ -75,85 +77,105 @@ function dlocate_option_error () {
   exit 1
 }
 
-IGNORE_CASE=""
+OPTION="DEFAULT"
+
 LAST_OPT=0
 
-OPTION="DEFAULT"
+# default to extended regexp
+RE_TYPE="-E"
+DCTRL_RE_TYPE="-e"
+RE_SEPARATOR="|"
+
+# default to case-sensitive
+IGNORE_CASE=""
+# default to non- word-based searches
+WORD_RE=""
+
+VERBOSE=0
 
 SEPARATOR='::::::::'
 PKGS=""
 for p in "$@"; do
-      case "$p" in
+    if [ "$LAST_OPT" -eq 1 ] ; then
+        PKGS="$PKGS$SEPARATOR$p"
+    else case "$p" in
 
         ('--')
-
-            if [ $LAST_OPT -eq 0 ] ; then
                 LAST_OPT=1
-            else
-                PKGS="$PKGS$SEPARATOR$p"
-            fi
             ;;
 
         (''|'-h'|'-H'|'--help')
-
-            if [ $LAST_OPT -eq 0 ] ; then
                 dlocate_help
-            else
-                PKGS="$PKGS$SEPARATOR$p"
-            fi
             ;;
 
-        ('-v'|'-V'|'--version')
-
-            if [ $LAST_OPT -eq 0 ] ; then
+        ('-V'|'--version')
                 dlocate_version
-            else
-                PKGS="$PKGS$SEPARATOR$p"
-            fi
             ;;
 
-        ('--ignore-case'|'-i')
-
-            if [ $LAST_OPT -eq 0 ] ; then
-                IGNORE_CASE='-i'
-            else
-                PKGS="$PKGS$SEPARATOR$p"
-            fi
+        ('-v'|'--verbose'|'--debug')
+                VERBOSE=1
             ;;
 
         ('-S'|'-L'|'-l'|'-s'|'-ls'|'-du'|'-conf'|'-lsconf'|'-md5sum'|'-md5check'|'-man'|'-lsman'|'-lsbin')
+                OPTION="$p"
+            ;;
 
-            if [ $LAST_OPT -eq 0 ] ; then
-                OPTION="$1"
-            else
-                PKGS="$PKGS$SEPARATOR$p"
-            fi
+        ('-i'|'--ignore-case')
+                IGNORE_CASE='-i'
+            ;;
+
+        ('-E'|'--extended-regexp')
+                RE_TYPE='-E'
+                DCTRL_RE_TYPE='-e'
+                RE_SEPARATOR='|'
+            ;;
+
+        ('-F'|'--fixed-strings')
+                RE_TYPE='-F'
+                RE_SEPARATOR="\n"
+            ;;
+            
+        ('-G'|'--basic-regexp')
+                RE_TYPE='-G'
+                DCTRL_RE_TYPE='-r'
+                RE_SEPARATOR='\\|'
+            ;;
+
+        ('-P'|'--perl-regexp')
+                RE_TYPE='-E'
+                RE_SEPARATOR='|'
+            ;;
+
+        ('-w'|'--word-regexp')
+                WORD_RE="-w"
             ;;
 
         (-*)
-            if [ $LAST_OPT -eq 0 ] ; then
                 dlocate_option_error $1
-            else
-                PKGS="$PKGS$SEPARATOR$p"
-            fi
             ;;
 
         (*)
-            PKGS="$PKGS$SEPARATOR$p"
+                PKGS="$PKGS$SEPARATOR$p"
             ;;
       esac
+    fi
 done
 
 PKGS=$(echo "$PKGS" | sed -e "s/^$SEPARATOR//")
-#echo $PKGS
+[ -z "$PKGS" ] && dlocate_help
 
-PKGS_REGEXP=$(echo "$PKGS" | sed -e "s/$SEPARATOR/|/g")
-#echo $PKGS_REGEXP
+PKGS_REGEXP=$(echo "$PKGS" | sed -e "s/$SEPARATOR/$RE_SEPARATOR/g")
 
-FILES_REGEXP="$PKGS_REGEXP"
-#echo $FILES_REGEXP
+FILES_REGEXP="($PKGS_REGEXP)"
+[ "$WORD_RE" = "-w" ] && FILES_REGEXP="\b$FILES_REGEXP\b"
 
-#exit
+PKGS=$(echo "$PKGS" | sed -e "s/$SEPARATOR/ /")
+
+if [ "$VERBOSE" = "1" ] ; then
+    echo "PKGS:" $PKGS
+    echo "RE_SEPARATOR:" $RE_SEPARATOR
+    echo "PKGS_REGEXP:" $PKGS_REGEXP
+fi
 
 [ -z "$PKGS_REGEXP" ] && PKGS_REGEXP='^$'
 
@@ -188,7 +210,9 @@ if [ "$OPTION" = '-l' ] ; then
 
     BODY_FMT_STRING="%-2s  %-${fieldw}.${fieldw}s %-${fieldw}.${fieldw}s %-${fieldd}.${fieldd}s\\n"
 
-    BODY=$( egrep $IGNORE_CASE -- "$PKGS_REGEXP" "$DPKGLIST" | \
+    [ "$VERBOSE" = "1" ] && echo RUNNING: grep $RE_TYPE $WORD_RE $IGNORE_CASE -- "$PKGS_REGEXP" "$DPKGLIST" 
+
+    BODY=$(grep $RE_TYPE $WORD_RE $IGNORE_CASE -- "$PKGS_REGEXP" "$DPKGLIST" | \
             awk -F'\t' "{ printf \"$BODY_FMT_STRING\", \$1, \$2, \$3, \$4 }" |
             sed -e 's/ *$//g'
           )
@@ -197,18 +221,31 @@ if [ "$OPTION" = '-l' ] ; then
 
 elif [ "$OPTION" = '-S' ] ; then
 
-    $LOCATE -d $DLOCATEDB $IGNORE_CASE -- $PKGS | egrep $IGNORE_CASE "^[-a-zA-Z0-9_.+]+:.*($FILES_REGEXP)"
+    if [ "$RE_TYPE" = '-F' ] ; then
+        echo "Error: -F Fixed String searches are incompatible with -S"
+        echo
+        exit 1
+    fi
+
+    [ "$VERBOSE" = "1" ] && echo RUNNING: grep $RE_TYPE $IGNORE_CASE"^[-a-zA-Z0-9_.+]+:.*$FILES_REGEXP" "$DLOCATEDB"
+    grep $RE_TYPE $IGNORE_CASE "^[-a-zA-Z0-9_.+]+:.*$FILES_REGEXP" "$DLOCATEDB"
     result=$?
 
 elif [ "$OPTION" = 'DEFAULT' ] ; then
 
-    $LOCATE -d $DLOCATEDB $IGNORE_CASE -- $PKGS
+    [ "$VERBOSE" = "1" ] && echo RUNNING: grep $RE_TYPE $IGNORE_CASE $WORD_RE "$PKGS_REGEXP" "$DLOCATEDB"
+    grep $RE_TYPE $IGNORE_CASE $WORD_RE "$PKGS_REGEXP" "$DLOCATEDB"
+    result=$?
+
+elif [ "$OPTION" = '-s' ] ; then
+    DCTRL_REGEXP="^($PKGS_REGEXP)$"
+
+    [ "$VERBOSE" = "1" ] && echo RUNNING: grep-dctrl -X -P $DCTRL_RE_TYPE $DCTRL_REGEXP /var/lib/dpkg/status 
+    grep-dctrl -P $DCTRL_RE_TYPE $DCTRL_REGEXP /var/lib/dpkg/status 
     result=$?
 
 else
-
     for PKG in $PKGS; do
-
         case "$OPTION" in
 
             '-L')
@@ -217,11 +254,6 @@ else
                 else
                     echo Package $PKG not installed or $PKG.list is empty. >&2
                 fi
-                ;;
-
-            '-s')
-                    grep-dctrl -X -P $PKG /var/lib/dpkg/status || \
-                    echo Package $PKG does not exist. >&2
                 ;;
 
             '-ls')
@@ -267,17 +299,20 @@ else
             '-lsman')
                 if [ -s $DPKG_INFO/$PKG.list ] ; then
                     dlocate -L $PKG | \
-                    grep '/man.*/.*[0-9]/'
+                    grep -E '/man[0-9]+/'
                 else
                     echo Package $PKG not installed or $PKG.list is empty. >&2
                 fi
-;;
+                ;;
 
             '-man')
                 if [ -s $DPKG_INFO/$PKG.list ] ; then
                     dlocate -L $PKG | \
-                        sed -n -e 's/\.gz$//' \
-                               -e '/\/man.*\/.*[0-9]/s/^.*\/\([^\/]*\)\.\(.*\)/\2 \1/p'
+                        grep -E '/man[0-9]+/' | \
+                        sed -e 's/\.gz$//' \
+                            -e 's:.*/::' \
+                            -e 's/\(^.*\)\.\(.*\)/\2 \1/' | \
+                        sort -u
                 else
                     echo Package $PKG not installed or $PKG.list is empty. >&2
                 fi
@@ -288,13 +323,13 @@ else
                     dlocate -L $PKG | \
                     xargs -r ls -lLd 2> /dev/null | \
                     grep -v "^[^-]" | \
-                    egrep '^-.{2,8}[xs]' | \
+                    grep -E '^-.{2,8}[xs]' | \
                     sed -e 's/.* \//\//' | \
                     xargs -r ls -1
                 else
                     echo Package $PKG not installed or $PKG.list is empty. >&2
                 fi
-;;
+                ;;
 
             '-md5check')
                 if [ -s $DPKG_INFO/$PKG.md5sums ] ; then
